[package]
name = "client-server"
version = "0.1.0"
edition = "2024"

[dependencies]
nix = { version = "=0.30.1", features = ["socket", "signal"] }
libc = "0.2.175"
serde = { version = "1.0.225", features = ["derive"] }
serde_json = "1.0.145"


